
export const CONSTANTS = Object.freeze({
    OTP_CACHE_TIME: 300,
    OTP_VERIFIED: "OTP verified successfully.",
    OTP_RESEND: "We've sent the OTP to your email again.",
    OTP_SEND: "Otp sent to email.",
    OTP_VERIFIED_FOR_FORGOT: "OTP verified for forgot password.",
    PASSWORD_RESET_SUCCESS: "Password reset successful.",
    PROFILE_UPDATED_SUCCESSFULLY:"Profile updated successfully.",
    EMAIL_UPDATED:"Email updated successfully.",
    ADDRESS_ADDED:"Address added successfully.",
    ADDRESS_FETCHED:"Addresses fetched successfully.",
    ADDRESS_UPDATED:"Address updated successfully.",
    ADDRESS_DELETED:"Address is deleted.",
    CUSTOMERS_FETCHED:"Customers details fetched successfully.",
    ADMIN_LOGIN: "Admin logged in successfully.",
    ADMIN_LOGOUT:"Admin Logged out successfully.",
    CATEGORY_ADDED:"Category added successfully.",
    CATEGORY_FETCHED_SUCCESSFULLY:"Category fetched successfully.",
    CATEGORY_UPDATED:"Category updated successfully.",
    CATEGORY_LIST_TOGGLED:"Category list toggled.",
    CATEGORY_DELETED :"Category is deleted.",
    PRODUCT_ADDED: "Product added successfully.",
    PRODUCT_UPDATED: "Product updated successfully.",
    PRODUCT_DELETED: "Product deleted successfully.",
    PRODUCT_FETCHED_SUCCESSFULLY: "Product fetched successfully.",
    PRODUCT_LIST_TOGGLED: "Product status toggled.",
    ORDER_CANCELLED_SUCCESSFULLY: "Order cancelled successfully.",
    ORDERS_FETCHED_SUCCESSFULLY: "Orders fetched successfully.",
    ORDER_STATUS_UPDATED: "Order status updated successfully.",
    ORDER_ITEM_STATUS_UPDATED: "Order item status updated successfully.",
    ORDER_PLACED_SUCCESSFULLY: "Order placed successfully.",
    ORDER_FETCHED_SUCCESSFULLY: "Order fetched successfully.",
    ORDER_RETURNED_SUCCESSFULLY: "Order returned successfully.",
    ORDER_ITEM_RETURNED_SUCCESSFULLY: "Order item returned successfully.",
    ORDER_ITEM_CANCELLED_SUCCESSFULLY: "Order item cancelled successfully.",
    WISHLIST_ADDED_SUCCESSFULLY: "Item added to wishlist successfully.",
    WISHLIST_FETCHED_SUCCESSFULLY: "Wishlist fetched successfully.",
    WISHLIST_REMOVED_SUCCESSFULLY: "Item removed from wishlist successfully.",
    WISHLIST_CLEARED_SUCCESSFULLY: "Wishlist cleared successfully.",
    WISHLIST_ITEM_MOVED_TO_CART_SUCCESSFULLY: "Item moved to cart successfully.",
    PAYMENT_VERIFIED_SUCCESSFULLY: "Payment verified successfully.",
    COUPON_CREATED: "Coupon created successfully",
    COUPON_FETCHED_SUCCESSFULLY: "Coupon fetched successfully",
    COUPON_UPDATED: "Coupon updated successfully",
    COUPON_DELETED: "Coupon deleted successfully",
    COUPON_LIST_TOGGLED: "Coupon list toggled",
    COUPON_UPDATED_SUCCESSFULLY: "Coupon updated successfully",
    OFFER_CREATED: "Offer created successfully",
    OFFER_FETCHED_SUCCESSFULLY: "Offer fetched successfully",
    OFFER_UPDATED: "Offer updated successfully",
    OFFER_DELETED: "Offer deleted successfully",
    OFFER_LIST_TOGGLED: "Offer list toggled",
    OFFER_UPDATED_SUCCESSFULLY: "Offer updated successfully",
    COUPON_APPLIED_SUCCESSFULLY: "Coupon applied successfully",
    COUPONS_FETCHED_SUCCESSFULLY: "Coupons fetched successfully",
    DASHBOARD_STATS_FETCHED_SUCCESSFULLY: "Dashboard stats fetched successfully",
    SALES_REPORT_FETCHED_SUCCESSFULLY: "Sales report fetched successfully",
    SALES_REPORT_DATA_FOR_DOWNLOAD_FETCHED_SUCCESSFULLY: "Sales report data for download fetched successfully",
});
