export const ERROR_MESSAGES = Object.freeze({
    EMAIL_ALREADY_EXISTS: "Email already exists.",
    INVALID_REFERRAL_CODE: "Referral code is invalid.",
    PASSWORD_MISMATCH: "Password must be match.",
    UNAUTHORIZED: "Unauthorized.",
    INVALID_PASSWORD: "Invalid Password.",
    INVALID_REFRESH_TOKEN: "Invalid refresh token.",
    INTERNAL_SERVER_ERROR: "Internal server Error.",
    USER_NOT_FOUND: "User not found.",
    OTP_EXPIRED: "OTP expired.",
    INVALID_OTP: "OTP is invalid.",
    ALREADY_VERIFIED: "OTP already verified.",
    USER_NOT_VERIFIED: "User is not verified.",
    USER_BLOCKED: "Your account is blocked",
    TOKEN_EXPIRED: "Token expired or invalid",
    ACCESS_TOKEN_MISSING: "Access token is missing.",
    EMAIL_IN_USE: "An account with this email already exists.",
    ADDRESS_NOT_FOUND: "Address is not found.",
    EMAIL_CANNOT_BE_CHANGED_FOR_GOOGLE: "Email cannot be changed for Google-authenticated accounts",
    ADMIN_ONLY: "Admin access only.",
    ACCESS_DENIED: "Access denied.",
    LOGIN_FROM_ADMIN_PANEL: "Login from admin panel.",
    USE_ADMIN_ENDPOINT: "Error : Use admin endpoint.",
    CATEGORY_IMAGE_REQUIRED: "Category image is required",
    INVALID_IMAGE_FORMAT: "Invalid image format.",
    CATEGORY_ALREADY_EXIST: "This category already exists.",
    PRODUCT_ALREADY_EXISTS: "Product already exists.",
    IMAGE_REQUIRED: "Thumbnail image is required.",
    PRODUCT_NOT_FOUND: "Product not found.",
    ATLEAST_TWO_IMAGES_REQUIRED: "At least 2 additional images are required.",
    MAXIMUM_FOUR_IMAGES_ALLOWED: "Maximum 4 product images allowed.",
    PRODUCT_CATEGORY_IS_NOT_LISTED: "Product category is not listed.",
    VARIANT_IS_NOT_FOUND: "Variant is not found.",
    NOT_ENOUGH_STOCK: "Not enough stock.",
    CART_NOT_FOUND: "Cart is not found.",
    ITEM_NOT_IN_CART: "Item is not in the cart.",
    WISHLIST_NOT_FOUND: "Wishlist not found.",
    ITEM_ALREADY_IN_WISHLIST: "Item is already in wishlist.",
    CART_EMPTY: "Cart is empty.",
    ORDER_NOT_FOUND: "Order not found.",
    ORDER_CANNOT_BE_CANCELLED: "Order cannot be cancelled in current status",
    STATUS_IS_REQUIRED: "Status is required",
    ADDRESS_AND_PAYMENT_METHOD_REQUIRED: "Address and Payment Method are required",
    PAYMENT_METHOD_NOT_SUPPORTED: "Payment method not supported",
    RETURN_REASON_REQUIRED: "Return reason is required",
    ITEM_NOT_FOUND: "Item not found",
    CANNOT_REVERT_ORDER_STATUS: "Cannot revert order status to a previous stage.",
    CANNOT_REVERT_ORDER_ITEM_STATUS: "Cannot revert order item status to a previous stage.",
    CANNOT_CHANGE_STATUS_OF_CANCELLED_ITEM: "Cannot change status of a Cancelled item.",
    DELIVERED_ITEMS_CAN_ONLY_BE_MARKED_AS_RETURNED: "Delivered items can only be marked as Returned.",
    CANNOT_CHANGE_STATUS_OF_CANCELLED_ORDER: "Cannot change status of a Cancelled order.",
    DELIVERED_ORDERS_CAN_ONLY_BE_MARKED_AS_RETURNED: "Delivered orders can only be marked as Returned.",
    RAZORPAY_ERROR: "Failed to initialize payment gateway.",
    INVALID_PAYMENT_SIGNATURE: "Invalid payment signature.",
});
